// client/src/components/dnd-5e-spells/components/SpellTable.tsx
import { Spell, TableColumn } from "../Types"

export const SpellTable = (props: { spells: Spell[], headerClicked(header: TableColumn): void }) => {
    const handleHeaderClick = (header: TableColumn) => {
        props.headerClicked(header)
    }
    return (
        <>
        <button onClick={() => props.headerClicked('name')}>click</button>
            {props.spells.map(spell => <div>{spell.name}</div>)}
            <table>
                <thead>
                    <tr>
                        <th key={`spell-th-name`} onClick={() => handleHeaderClick('name')}>Name</th>
                    </tr>
                </thead>
            </table>
        </>
    )
}

// svelte-app/src/feature/dndspells/components/SpellTable.svelte
<script lang="ts">
	import type { Spell, TableColumn } from '../types';
	import SpellTableRow from './SpellTableRow.svelte';

	export let data: Spell[];

	export let headerClicked: (header: TableColumn) => void;
</script>

<table>
	<tr>
		<th on:click={() => headerClicked('name')}>Name</th>
		<th on:click={() => headerClicked('school')}>School</th>
		<th on:click={() => headerClicked('class')}>Class</th>
		<th>Description</th>
	</tr>
	{#if data}
		{#each data as spell}
			<SpellTableRow {spell} />
		{/each}
	{/if}
</table>
